version: "3.1"
services:
  db:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/pgsql/data/pgdata
  odoo:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file: .env
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
volumes:
  data:
  db:
